sudo: required
services:
  - docker 

before_install:
  - docker build -t loki194/docker-react-continuous-integraion -f Dockerfile.dev .
script:
  - docker run loki194/docker-react-continuous-integraion npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-327326504583"
  bucket_path: "docker-react"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  on:
    branch: master
